### ISSUE TITLE
学习成本和解析json 数据的复杂度如何做选择？

### ISSUE THREAD

**Issue by VectorWen** [niuxiaowei/SimpleJavaJsBridge#2]
学习成本和解析json 数据的复杂度如何做选择？

很认真看完README，好像无法快速写出一个DEMO，下一个想法就是有空再回来看。学习成本比起使用我熟悉的json，我会选择json。等我有空再回头看这库的使用方法。

但很多时候我们都是这样错过一个很好的使用方法。IT 界总是说要学习很多很多新的知识，更新换代要我们一直学习，不然就会被out。学习不应该是一件快乐的事情吗？怎么感觉被压的喘不过气了呢？

**Comment by niuxiaowei** [comment]
我已经尽量的让这个库使用起来最简单，不管什么新知识都是有学习成本的，关键是学习了以后给自己能带来多大收益，多大方便。像retrofit学习成本其实也不小，关键它带来的收益很大。
